### ISSUE TITLE
Inquiry ICI Model 

### ISSUE THREAD

**Issue by 1002wu** [jeremyzhangsq/ICI#1]
I noticed that while the benchmark details are readily available, the ICI model methodology is not explicitly outlined. Could you kindly share any documentation or insights on ICI model?

**Comment by jeremyzhangsq** [comment]
Hi @1002wu,
For the detailed methodology, please refer to our work at WWW'24:
https://dl.acm.org/doi/10.1145/3589335.3648337.

Best,
Shiqi

**Comment by 1002wu** [comment]
Would it be possible for you to provide the detailed code for the ICI model ?

**Comment by jeremyzhangsq** [comment]
Please refer to the code in model.py at the utils folder.

**Comment by 1002wu** [comment]
While reviewing the utils/model.py file in your GitHub repository, I noticed that the ICI model is not included. Could you kindly provide the code for this model? Is the ICR model in the code the same as the ICI model in the paper?

**Comment by jeremyzhangsq** [comment]
Yes. ICI is ICR. 
To avoid ambiguity, I have renamed the related functions and updated the repo.

**Comment by 1002wu** [comment]
Thanks!

**Comment by jeremyzhangsq** [comment]
welcome:D
